version: '3.0'

services:
  config-server:
    build:
      context: ./configserver
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8075:8075"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/duygu2/hr-config-files
    networks:
      - common

  discovery-server:
    build:
      context: ./discoveryserver
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8075
    networks:
      - common

  gateway-server:
    build:
      context: ./gatewayserver
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8075
    networks:
      - common

  employee-service:
    build:
      context: ./employeeservice
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}

    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - employee-db
      - discovery-server
      - config-server
      - gateway-server
    networks:
      - common
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8075
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-db:5432/employeeservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test

  employee-db:
    image: postgres
    container_name: employee-db-prod
    environment:
      POSTGRES_DB: employeeservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - employee_data_prod:/var/lib/postgresql/data
    networks:
      - common

volumes:
  employee_data_prod:


networks:
  common:
    driver: bridge